version: "3"

services:
  spabase:
    image: registry.tompaton.com/tompaton/spabase
    env_file:
      - production.env
    networks:
      - www
    volumes:
      - ./data:/data
    restart: unless-stopped

networks:
  www:
    external:
      name: www
